name = input("What is your name?")
print(name)
age = input("How old are you? ")
print(age)
color = input("What's your favorite color?")
print(color)
print("Hello", name , "you are", age , "years old and your favorite color is", color )